# 生产环境 9595
server:
  port: 9595
spring:
  datasource:
    username: ENC(cvWQcQZMg/EULl6ZDfzyGA==)
    password: ENC(LQu67TkSLOlBnBxxe6Hx6kU7+nykxhWQ)
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(X+eRXgfOsS3TsSdC+fl/UTx24Dtex/JKhzYdJuexwn6aLvYCMrISeJ+Hy0uVBd6XtWqwtgW3dPAWlAVb/N/3QeGdtwF50QGFLbGmcpIbUhRPLn106HTIhw==)