# 测试环境 9999
server:
  port: 9999
spring:
  datasource:
    username: ENC(XRx2m/3zjAEDdUlkQOwgsadkLuH4YJTJ)
    password: ENC(hzXTmV3Pg3Yr92RySUF8RV2/W93HVjF8)
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(Rt41dEMTB88hD0xq+lsu1hSI175RGKdf5oz/3u5I+0mj5MR2V5OIY0dYHz5MURrbrNFIWE4Al/MbBBJSEmt+qs1bMNIsVu0DmadIkYUrvoXza3fJq1HPguL+qRlHzdFL)