# 开发环境 9090
server:
  port: 9090
spring:
  datasource:
    username: ENC(nYHpp5gwPNFFy0wHj5KKZrRGMMWNmeNY)
    password: ENC(0ZzE7SX9yQWl6PRSEaM9OMM5lXOWBLqO)
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(nZ8UoGtF3jZETd7TWWKeLaNRPlzNlMKIRlKD9MFBH/V3z9Cfs4DKSEqgNfgjiGlE5E6ge8VCSdZJSm6a3Kt47GVDj9MmXxTueTtTL8rwtUM4emez/FI5gomX8rx5d2Ys)
logging:
  level:
    com.example.demo.dao: debug
mybatis:
  # spring boot集成mybatis的方式打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl