# 测试环境 9999
server:
  port: 9999
spring:
  datasource:
    username: qxwl_test
    password: mysqlroot
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.102.208.247:3306/qxwl_test?useUnicode=true&characterEncoding=utf-8