server:
  port: 8080
spring:
  profiles:
    active: dev
  datasource:
    username: qxwl
    password: mysqlroot
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.102.208.247:3306/qxwl?useUnicode=true&characterEncoding=utf-8
  mvc:
    view:
      prefix: /
      suffix: .html