server:
  port: 8080
spring:
  profiles:
    active: dev
  datasource:
    username: qxwl
    password: mysqlroot
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.102.208.247:3306/qxwl?useUnicode=true&characterEncoding=utf-8
  mvc:
    view:
      prefix: /
      suffix: .html
## Redis配置 - start
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 47.102.208.247
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: "wllt_qxwl@123"
    # 连接超时时间（毫秒）
    timeout: 5000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
    ## Redis配置 - end


## 其它配置 - start
config:
  # JWT认证加密私钥(Base64加密)
  encrypt-jwtKey: U0JBUElOENhspJrzkyNjQ1NA
  # AccessToken过期时间(秒)
  accessToken-expireTime: 600
  # RefreshToken过期时间(秒)
  refreshToken-expireTime: 604800
## 其它配置 - end

#开发权限
ignored:
  urls:
    - /qxwl/user/wlltUser/loginOut
    - /qxwl/user/wlltUser/register
    - /qxwl/user/wlltUser/loginUp
    - /qxwl/sys/**
    - /**/*.html
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.icon

